"""add_provider_facility_id_to_campgrounds

Revision ID: 5e1b3553216e
Revises: b2c3d4e5f6a7
Create Date: 2026-06-09 11:58:04.172577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5e1b3553216e'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campgrounds', sa.Column('provider_facility_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campgrounds', 'provider_facility_id')
    # ### end Alembic commands ###
